import { VerticalBox, HorizontalBox, LineEdit, Button, ComboBox } from "std-widgets.slint";

export global MainMenu {
    callback name();
    callback balance();
}

export component MainMenuView {
    in-out property <int> current-item: 0;
    in-out property <[string]> aircraft_list;
    in-out property <string> selected_aircraft;

    callback aircraft_changed();
    callback balance_call();

    VerticalBox {
        input := HorizontalBox {

            aircraft_combo := ComboBox {
                width: 200px;
                height: 50px;
                model: root.aircraft_list;
                current-value <=> selected_aircraft;
                selected(current-value) => {
                    root.aircraft_changed();
                }
            }
        }

        info := VerticalBox {
            Text {
                //text: "Aircraft : " + aircraft.name + " / " + aircraft.aircraft-type + "-" + aircraft.power;
                font-size: 20pt;
            }

            balance_btn := Button {
                text: "Balance";
                width: 100px;
                height: 50px;
                clicked => {
                    root.current-item = 1;
                    root.balance_call();
                }
            }
            visible: true;
        }
    }
}
